### POST
POST http://127.0.0.1:5000/api/add_hour_entry HTTP/1.1
content-type: application/json

{
  "doneAt": "2026-12-11",
  "project": "PR2500001044",
  "quantity": 6.35,
  "user": 1
}


### GET
GET http://127.0.0.1:5000/api/hour_entry HTTP/1.1


###
GET http://127.0.0.1:5000/api/hour_entry?user=2 HTTP/1.1


###
GET http://127.0.0.1:5000/api/hour_entry?id=15 HTTP/1.1


### PATCH
PATCH http://127.0.0.1:5000/api/update_hour_entry?id=22
content-type: application/json

{
  "project": "PR2500000825",
  "quantity": "6.35",
  "user": "5"
}


### DELETE
DELETE  http://127.0.0.1:5000/api/delete_hour_entry?id=7